

module AbsCCS where

-- Haskell module generated by the BNF converter




newtype LIdent = LIdent String deriving (Eq, Ord, Show, Read)
data P
    = PLUS P P
    | PAR P P
    | BANG P
    | TAUP P
    | INP LIdent P
    | OUT LIdent P
    | NULL
    | NEW LIdent P
  deriving (Eq, Ord, Show, Read)

