module SkelCCS where

-- Haskell module generated by the BNF converter

import AbsCCS
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transLIdent :: LIdent -> Result
transLIdent x = case x of
  LIdent string -> failure x
transP :: P -> Result
transP x = case x of
  PLUS p1 p2 -> failure x
  PAR p1 p2 -> failure x
  BANG p -> failure x
  TAUP p -> failure x
  INP lident p -> failure x
  OUT lident p -> failure x
  NULL -> failure x
  NEW lident p -> failure x

